### ISSUE TITLE
Downloaded videos and songs are overriding each other when having the same title

### ISSUE THREAD

**Issue by LeonhardSchwertfeger** [btschwertfeger/ytdownloader#7]
Songs are downloaded simultaneously instead of one after the other. 
As a result, sometimes .mp4/mp3 files are in the folder several times and are then reassembled, 
deleted and started all over again until the download is finished.

Example:

[download] Downloading item 25 of 72
[youtube] Extracting URL: https://www.youtube.com/watch?v=6jJkdRaa04g
[youtube] 6jJkdRaa04g: Downloading webpage
[youtube] 6jJkdRaa04g: Downloading ios player API JSON
[youtube] 6jJkdRaa04g: Downloading mweb player API JSON
[youtube] 6jJkdRaa04g: Downloading m3u8 information
Deleting original file /Users/leonhard/Downloads/Musik/Phaxe & Morten Granau - 7 Seas (official audio) 432 Records.webm (pass -k to keep)
Deleting original file /Users/leonhard/Downloads/Musik/YES - Owner of a Lonely Heart (Official Music Video).webm (pass -k to keep)
[download] Downloading item 20 of 100

**Comment by btschwertfeger** [comment]
Does multiple different downloads infer each other by using the same cache/tmp files? 

Before thinking of implementing a sequential approach, we should check if that behavoir can be fixed by renaming those cache/tmp files.
